# Generated by Django 4.2 on 2025-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='video_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
