# Generated by Django 4.2 on 2025-03-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_music_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='video_url',
        ),
    ]
