# Generated by Django 4.2 on 2025-03-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
