# Generated by Django 4.2 on 2025-03-24 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
